apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      -name: test
       image: app-image
       ports:
         - containerPort: 9090
       env:
         - name: MY_PASSWORD
           valueFrom:
             secretKeyRef:
               name: credentials
               key: password
